import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../supabaseClient';
import { useAuth } from '../context/AuthContext';
import ForestPlot from '../components/ForestPlot';
import { RATE_SCALE_OPTIONS, WEIGHTING_OPTIONS, runSynthesis } from '../lib/synthesis';
import { slugify } from '../lib/identifiers';

export default function SynthesizePage(){
  const {user}=useAuth(); const [rows,setRows]=useState([]); const [concepts,setConcepts]=useState([]); const [outcome,setOutcome]=useState(''); const [cohort,setCohort]=useState(''); const [yearMin,setYearMin]=useState(''); const [yearMax,setYearMax]=useState(''); const [weighting,setWeighting]=useState('raw'); const [rateScale,setRateScale]=useState('per_1000_days'); const [percent,setPercent]=useState(true); const [msg,setMsg]=useState('');
  useEffect(()=>{load();},[]);
  async function load(){const [r,c]=await Promise.all([supabase.from('rse_synthesis_rows').select('*').limit(5000),supabase.from('rse_outcome_concepts').select('id,label,default_outcome_type').order('label')]);setRows(r.data||[]);setConcepts(c.data||[]);if(!outcome&&c.data?.[0])setOutcome(c.data[0].id);}
  const filtered=useMemo(()=>rows.filter(r=>{if(outcome&&r.outcome_concept_id!==outcome)return false;if(cohort&&!(r.cohort_label||'').toLowerCase().includes(cohort.toLowerCase())&&!(r.intervention||'').toLowerCase().includes(cohort.toLowerCase()))return false;if(yearMin&&Number(r.publication_year)<Number(yearMin))return false;if(yearMax&&Number(r.publication_year)>Number(yearMax))return false;return true;}),[rows,outcome,cohort,yearMin,yearMax]);
  const model=useMemo(()=>runSynthesis(filtered,{weighting,rateScale,proportionAsPercent:percent}),[filtered,weighting,rateScale,percent]);
  const type=filtered[0]?.outcome_type; const suffix=type==='proportion'&&percent?'%':type==='rate'?` (${RATE_SCALE_OPTIONS.find(x=>x[0]===rateScale)?.[1]})`:'';
  async function saveLive(){if(!user){setMsg('Sign in to save a public live comparison.');return;}const title=window.prompt('Title for this live evidence page',concepts.find(x=>x.id===outcome)?.label||'Live evidence');if(!title)return;const payload={slug:`${slugify(title)}-${Math.random().toString(36).slice(2,7)}`,title,description:'Live synthesis from community-selected evidence in Ready...Set...Evidence.',outcome_concept_id:outcome,filters:{cohort_contains:cohort||null,year_min:yearMin?Number(yearMin):null,year_max:yearMax?Number(yearMax):null},weighting,rate_scale:rateScale,proportion_as_percent:percent,owner_user_id:user.id,is_public:true};const {data,error}=await supabase.from('rse_live_views').insert(payload).select().single();setMsg(error?error.message:`Live view created: /live/${data.slug}`);}
  return <section><div className="page-title"><div><div className="eyebrow">Reusable synthesis</div><h1>Build a comparison from the Commons</h1><p>The synthesis uses the community-preferred extraction for each evidence slot. RAW uses the mean community appraisal on the existing 1-best to 4-worst quality scale.</p></div></div>
    <div className="card filter-grid"><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">All outcomes</option>{concepts.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Cohort/intervention contains<input value={cohort} onChange={e=>setCohort(e.target.value)} placeholder="e.g., tunneled catheter"/></label><label>Year from<input value={yearMin} onChange={e=>setYearMin(e.target.value)}/></label><label>Year to<input value={yearMax} onChange={e=>setYearMax(e.target.value)}/></label><label>Weighting<select value={weighting} onChange={e=>setWeighting(e.target.value)}>{WEIGHTING_OPTIONS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Rate display<select value={rateScale} onChange={e=>setRateScale(e.target.value)}>{RATE_SCALE_OPTIONS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={percent} onChange={e=>setPercent(e.target.checked)}/> Show proportions as percent</label><button className="button secondary" onClick={saveLive}>Save as live evidence page</button></div>
    {msg&&<div className="notice">{msg}</div>}
    <div className="metric-grid"><div className="metric-card"><div className="metric-value">{model.k}</div><div className="metric-label">Studies</div></div><div className="metric-card"><div className="metric-value">{Number.isFinite(model.mean)?model.mean.toFixed(3):'—'}{suffix}</div><div className="metric-label">Pooled estimate</div></div><div className="metric-card"><div className="metric-value">{Number.isFinite(model.ciLower)?`${model.ciLower.toFixed(3)} to ${model.ciUpper.toFixed(3)}`:'—'}</div><div className="metric-label">95% CI</div></div><div className="metric-card"><div className="metric-value">{Number.isFinite(model.tau2)?model.tau2.toFixed(4):'—'}</div><div className="metric-label">Tau²</div></div></div>
    <div className="card"><h2>Forest plot</h2><ForestPlot studies={model.studies} pooled={model}/></div>
    <div className="card"><h2>Included consensus evidence</h2><div className="table-wrap"><table><thead><tr><th>Study</th><th>Year</th><th>Cohort</th><th>Outcome</th><th>Timepoint</th><th>Community appraisal</th><th>Votes</th></tr></thead><tbody>{filtered.map(r=><tr key={r.extraction_id}><td>{r.work_title}</td><td>{r.publication_year}</td><td>{r.cohort_label}</td><td>{r.outcome_label}</td><td>{r.timepoint_label||'—'}</td><td>{Number(r.community_quality_score).toFixed(2)} / 4 (n={r.appraisal_count})</td><td>{r.vote_count}</td></tr>)}</tbody></table></div></div>
  </section>
}
