import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Check, Flag, Plus, Vote } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { useAuth } from '../context/AuthContext';
import { formatDate, slugify } from '../lib/identifiers';

const num=v=>v===''||v==null?null:Number(v);

export default function WorkPage(){
  const {id}=useParams(); const {user,profile}=useAuth();
  const [work,setWork]=useState(null),[authors,setAuthors]=useState([]),[cohorts,setCohorts]=useState([]),[concepts,setConcepts]=useState([]),[slots,setSlots]=useState([]),[extractions,setExtractions]=useState([]),[votes,setVotes]=useState([]),[appraisals,setAppraisals]=useState([]),[frameworks,setFrameworks]=useState([]),[challenges,setChallenges]=useState([]),[msg,setMsg]=useState('');
  const [cohortForm,setCohortForm]=useState({label:'Overall cohort',patient_population:'',intervention:'',comparator:'',sample_size:''});
  const [ev,setEv]=useState({cohort_id:'',outcome_label:'',outcome_type:'proportion',timepoint_label:'',subgroup_label:'',units:'',mean:'',sd:'',n:'',events:'',total_exposure:'',reported_value:'',source_locator:'',extraction_notes:''});
  const [app,setApp]=useState({framework_id:'',quality_score:'2',rationale:''});
  useEffect(()=>{load();},[id,user?.id]);
  async function load(){
    const [w,a,c,o,s,e,v,ap,f,ch]=await Promise.all([
      supabase.from('rse_works').select('*').eq('id',id).single(),
      supabase.from('rse_work_authors').select('*').eq('work_id',id).order('author_order'),
      supabase.from('rse_cohorts').select('*').eq('work_id',id).order('created_at'),
      supabase.from('rse_outcome_concepts').select('*').order('label'),
      supabase.from('rse_evidence_slots').select('*').eq('work_id',id).order('created_at'),
      supabase.from('rse_extractions').select('*,creator:rse_profiles!created_by(username,display_name)').in('slot_id',(await supabase.from('rse_evidence_slots').select('id').eq('work_id',id)).data?.map(x=>x.id)||['00000000-0000-0000-0000-000000000000']).order('created_at'),
      supabase.from('rse_extraction_votes').select('*').in('slot_id',(await supabase.from('rse_evidence_slots').select('id').eq('work_id',id)).data?.map(x=>x.id)||['00000000-0000-0000-0000-000000000000']),
      supabase.from('rse_appraisals').select('*,profile:rse_profiles!user_id(username,display_name),framework:rse_appraisal_frameworks(name)').eq('work_id',id).order('created_at'),
      supabase.from('rse_appraisal_frameworks').select('*').eq('is_public',true).order('name'),
      supabase.from('rse_challenges').select('*').in('extraction_id',(await supabase.from('rse_extractions').select('id').in('slot_id',(await supabase.from('rse_evidence_slots').select('id').eq('work_id',id)).data?.map(x=>x.id)||['00000000-0000-0000-0000-000000000000'])).data?.map(x=>x.id)||['00000000-0000-0000-0000-000000000000']).order('created_at',{ascending:false})
    ]);
    setWork(w.data);setAuthors(a.data||[]);setCohorts(c.data||[]);setConcepts(o.data||[]);setSlots(s.data||[]);setExtractions(e.data||[]);setVotes(v.data||[]);setAppraisals(ap.data||[]);setFrameworks(f.data||[]);setChallenges(ch.data||[]);
    if(!ev.cohort_id&&c.data?.[0])setEv(x=>({...x,cohort_id:c.data[0].id})); if(!app.framework_id&&f.data?.[0])setApp(x=>({...x,framework_id:f.data[0].id}));
  }
  const conceptMap=useMemo(()=>new Map(concepts.map(x=>[x.id,x])),[concepts]); const cohortMap=useMemo(()=>new Map(cohorts.map(x=>[x.id,x])),[cohorts]);
  const voteCount=id=>votes.filter(v=>v.extraction_id===id).length; const myVote=slotId=>votes.find(v=>v.slot_id===slotId&&v.user_id===user?.id)?.extraction_id;
  async function claim(){const {data,error}=await supabase.rpc('rse_claim_authorship',{p_work_id:id});setMsg(error?error.message:`Authorship claim ${data?.status||'submitted'}.`);}
  async function addCohort(e){e.preventDefault();if(!user)return;const {error}=await supabase.from('rse_cohorts').insert({...cohortForm,sample_size:num(cohortForm.sample_size),work_id:id,created_by:user.id});setMsg(error?error.message:'Cohort added.');if(!error){setCohortForm({label:'',patient_population:'',intervention:'',comparator:'',sample_size:''});load();}}
  async function findOrCreateConcept(label,type){let existing=concepts.find(x=>x.label.toLowerCase()===label.toLowerCase());if(existing)return existing;const {data,error}=await supabase.from('rse_outcome_concepts').insert({label,slug:`${slugify(label)}-${Math.random().toString(36).slice(2,6)}`,default_outcome_type:type,created_by:user.id}).select().single();if(error)throw error;return data;}
  async function addExtraction(e){e.preventDefault();if(!user)return;setMsg('');try{const concept=await findOrCreateConcept(ev.outcome_label.trim(),ev.outcome_type);let {data:slot}=await supabase.from('rse_evidence_slots').select('*').eq('work_id',id).eq('cohort_id',ev.cohort_id).eq('outcome_concept_id',concept.id).eq('outcome_type',ev.outcome_type).ilike('timepoint_label',ev.timepoint_label||'').ilike('subgroup_label',ev.subgroup_label||'').maybeSingle();if(!slot){const r=await supabase.from('rse_evidence_slots').insert({work_id:id,cohort_id:ev.cohort_id,outcome_concept_id:concept.id,outcome_type:ev.outcome_type,timepoint_label:ev.timepoint_label||'',subgroup_label:ev.subgroup_label||'',units:ev.units||null,created_by:user.id}).select().single();if(r.error)throw r.error;slot=r.data;}
      const payload={slot_id:slot.id,mean:num(ev.mean),sd:num(ev.sd),n:num(ev.n),events:num(ev.events),total_exposure:num(ev.total_exposure),reported_value:num(ev.reported_value),source_locator:ev.source_locator||null,extraction_notes:ev.extraction_notes||null,created_by:user.id};const r=await supabase.from('rse_extractions').insert(payload).select().single();if(r.error)throw r.error;await supabase.from('rse_extraction_votes').upsert({slot_id:slot.id,extraction_id:r.data.id,user_id:user.id});setMsg('Extraction added. If an identical extraction already existed, use the existing extraction and confirm it instead.');setEv(x=>({...x,outcome_label:'',timepoint_label:'',subgroup_label:'',mean:'',sd:'',n:'',events:'',total_exposure:'',reported_value:'',source_locator:'',extraction_notes:''}));load();}catch(err){setMsg(err.code==='23505'?'That evidence slot or exact extraction already exists. Confirm the existing extraction instead.':err.message);}}
  async function vote(slotId,extractionId){if(!user)return;await supabase.from('rse_extraction_votes').upsert({slot_id:slotId,extraction_id:extractionId,user_id:user.id},{onConflict:'slot_id,user_id'});load();}
  async function challenge(extractionId){if(!user)return;const rationale=window.prompt('Describe the problem with this extraction and the evidence supporting your challenge.');if(!rationale)return;const reason=window.prompt('Reason code: numerator, denominator, outcome, cohort, timepoint, calculation, source, other','other')||'other';const {error}=await supabase.from('rse_challenges').insert({extraction_id:extractionId,created_by:user.id,reason_code:reason,rationale});setMsg(error?error.message:'Challenge submitted.');load();}
  async function editExtraction(x){if(user?.id!==x.created_by)return;const reason=window.prompt('Why are you changing this extraction?','Correction after review');if(!reason)return;const events=window.prompt('Events',x.events??'');const n=window.prompt('N',x.n??'');const exposure=window.prompt('Total exposure',x.total_exposure??'');const mean=window.prompt('Mean',x.mean??'');const sd=window.prompt('SD',x.sd??'');const {error}=await supabase.from('rse_extractions').update({events:num(events),n:num(n),total_exposure:num(exposure),mean:num(mean),sd:num(sd),last_change_reason:reason}).eq('id',x.id);setMsg(error?error.message:'Extraction updated and a new immutable version was recorded.');load();}
  async function resolveChallenge(ch,status){const notes=window.prompt(`Resolution note for ${status}:`,'');const {error}=await supabase.from('rse_challenges').update({status,resolution_notes:notes||null,resolved_by:user.id,resolved_at:new Date().toISOString()}).eq('id',ch.id);setMsg(error?error.message:`Challenge ${status}.`);load();}
  async function saveAppraisal(e){e.preventDefault();if(!user)return;const {error}=await supabase.from('rse_appraisals').upsert({work_id:id,framework_id:app.framework_id,user_id:user.id,quality_score:Number(app.quality_score),rationale:app.rationale||null},{onConflict:'work_id,framework_id,user_id'});setMsg(error?error.message:'Appraisal saved.');load();}
  if(!work)return <div className="empty-state">Loading paper…</div>;
  return <section><div className="page-title"><div><div className="eyebrow">{work.work_type?.replaceAll('_',' ')} {work.publication_year?`• ${work.publication_year}`:''}</div><h1>{work.title}</h1><p>{[work.journal,work.doi&&`DOI ${work.doi}`,work.pmid&&`PMID ${work.pmid}`].filter(Boolean).join(' • ')}</p></div>{user&&<button className="button secondary" onClick={claim}>Claim authorship</button>}</div>{work.abstract&&<div className="card"><h2>Abstract</h2><p>{work.abstract}</p></div>}{msg&&<div className="notice">{msg}</div>}
    <div className="two-column"><section><div className="card"><h2>Authors</h2>{authors.map(a=><div key={a.id}>{a.full_name} {a.orcid&&<span className="muted tiny">ORCID {a.orcid}</span>}</div>)}{!authors.length&&<div className="muted">No author metadata.</div>}</div><div className="section-heading"><div><div className="eyebrow">Structured evidence</div><h2>Evidence slots and competing extractions</h2></div></div>{slots.map(s=><div className="card evidence-slot" key={s.id}><div className="slot-head"><div><h3>{conceptMap.get(s.outcome_concept_id)?.label||'Outcome'}</h3><div className="muted">{cohortMap.get(s.cohort_id)?.label} {s.timepoint_label&&`• ${s.timepoint_label}`} {s.subgroup_label&&`• ${s.subgroup_label}`} • {s.outcome_type}</div></div><span className="tag">{extractions.filter(x=>x.slot_id===s.id).length} proposal(s)</span></div>{extractions.filter(x=>x.slot_id===s.id).map(x=><div className={`extraction-row ${myVote(s.id)===x.id?'selected':''}`} key={x.id}><div><strong>{s.outcome_type==='continuous'?`mean ${x.mean} (SD ${x.sd}), n=${x.n}`:s.outcome_type==='rate'?`${x.events} events / ${x.total_exposure} exposure`:`${x.events}/${x.n}`} </strong><div className="muted tiny">Source: {x.source_locator||'not specified'} • Extracted by {x.creator?.display_name||x.creator?.username||'contributor'} • {voteCount(x.id)} confirmations</div>{x.extraction_notes&&<div className="tiny">{x.extraction_notes}</div>}</div><div className="row-actions">{user&&<button className="button mini" onClick={()=>vote(s.id,x.id)}><Vote size={14}/> {myVote(s.id)===x.id?'Confirmed':'Confirm'}</button>}{user&&<button className="button mini ghost" onClick={()=>challenge(x.id)}><Flag size={14}/> Challenge</button>}{user?.id===x.created_by&&<button className="button mini ghost" onClick={()=>editExtraction(x)}>Edit</button>}</div></div>)}</div>)}{!slots.length&&<div className="empty-state">No structured endpoints yet. Be the first contributor.</div>}</section>
      <aside>{user&&<><form className="card form-stack" onSubmit={addCohort}><h2><Plus size={17}/> Add cohort</h2><label>Label<input required value={cohortForm.label} onChange={e=>setCohortForm({...cohortForm,label:e.target.value})}/></label><label>Patient population<input value={cohortForm.patient_population} onChange={e=>setCohortForm({...cohortForm,patient_population:e.target.value})}/></label><label>Intervention/device/drug<input value={cohortForm.intervention} onChange={e=>setCohortForm({...cohortForm,intervention:e.target.value})}/></label><label>Comparator<input value={cohortForm.comparator} onChange={e=>setCohortForm({...cohortForm,comparator:e.target.value})}/></label><label>Sample size<input value={cohortForm.sample_size} onChange={e=>setCohortForm({...cohortForm,sample_size:e.target.value})}/></label><button className="button secondary">Add cohort</button></form>
        <form className="card form-stack" onSubmit={addExtraction}><h2>Extract endpoint</h2><label>Cohort<select required value={ev.cohort_id} onChange={e=>setEv({...ev,cohort_id:e.target.value})}><option value="">Select</option>{cohorts.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label>Outcome concept<input required list="outcomes" value={ev.outcome_label} onChange={e=>setEv({...ev,outcome_label:e.target.value})}/><datalist id="outcomes">{concepts.map(o=><option value={o.label} key={o.id}/>)}</datalist></label><label>Type<select value={ev.outcome_type} onChange={e=>setEv({...ev,outcome_type:e.target.value})}><option value="proportion">Proportion</option><option value="rate">Rate</option><option value="continuous">Continuous</option></select></label><label>Timepoint<input value={ev.timepoint_label} onChange={e=>setEv({...ev,timepoint_label:e.target.value})} placeholder="e.g., 90 days"/></label><label>Subgroup<input value={ev.subgroup_label} onChange={e=>setEv({...ev,subgroup_label:e.target.value})}/></label>{ev.outcome_type==='continuous'?<><label>Mean<input value={ev.mean} onChange={e=>setEv({...ev,mean:e.target.value})}/></label><label>SD<input value={ev.sd} onChange={e=>setEv({...ev,sd:e.target.value})}/></label><label>N<input value={ev.n} onChange={e=>setEv({...ev,n:e.target.value})}/></label></>:ev.outcome_type==='rate'?<><label>Events<input value={ev.events} onChange={e=>setEv({...ev,events:e.target.value})}/></label><label>Total exposure<input value={ev.total_exposure} onChange={e=>setEv({...ev,total_exposure:e.target.value})}/></label></>:<><label>Events<input value={ev.events} onChange={e=>setEv({...ev,events:e.target.value})}/></label><label>N<input value={ev.n} onChange={e=>setEv({...ev,n:e.target.value})}/></label></>}<label>Source location<input value={ev.source_locator} onChange={e=>setEv({...ev,source_locator:e.target.value})} placeholder="Table 2, p. 7"/></label><label>Notes<textarea rows="3" value={ev.extraction_notes} onChange={e=>setEv({...ev,extraction_notes:e.target.value})}/></label><button className="button primary">Add extraction</button></form></>}
        <div className="card"><h2>Community appraisal</h2>{appraisals.map(a=><div className="appraisal-row" key={a.id}><strong>{a.quality_score}/4</strong><div>{a.profile?.display_name||a.profile?.username} <span className="muted tiny">{a.framework?.name}</span></div>{a.rationale&&<div className="muted tiny">{a.rationale}</div>}</div>)}{user&&<form className="form-stack compact" onSubmit={saveAppraisal}><label>Framework<select value={app.framework_id} onChange={e=>setApp({...app,framework_id:e.target.value})}>{frameworks.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><label>Quality score<select value={app.quality_score} onChange={e=>setApp({...app,quality_score:e.target.value})}><option value="1">1, strongest</option><option value="2">2</option><option value="3">3</option><option value="4">4, weakest</option></select></label><label>Rationale<textarea rows="2" value={app.rationale} onChange={e=>setApp({...app,rationale:e.target.value})}/></label><button className="button secondary">Save independent appraisal</button></form>}</div>
        <div className="card"><h2>Open challenges</h2>{challenges.filter(c=>c.status==='open').map(c=>{const x=extractions.find(e=>e.id===c.extraction_id);return <div className="challenge" key={c.id}><strong>{c.reason_code}</strong><p>{c.rationale}</p><div className="muted tiny">{formatDate(c.created_at)}</div>{user?.id===x?.created_by&&<div className="row-actions"><button className="button mini" onClick={()=>resolveChallenge(c,'accepted')}><Check size={13}/> Accept</button><button className="button mini ghost" onClick={()=>resolveChallenge(c,'rejected')}>Reject</button></div>}</div>})}{!challenges.some(c=>c.status==='open')&&<div className="muted">No open challenges.</div>}</div>
      </aside></div>
  </section>
}
